development: &default
  adapter: postgresql
  database: dummy_development
  encoding: unicode
  host: localhost
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>


test:
  <<: *default
  database: dummy_test
